apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.timescale.name }}
  labels:
    app: {{ .Values.timescale.name }}
    version: {{ .Values.timescale.version }}
spec:
  serviceName: {{ .Values.timescale.name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.timescale.name }}
      version: {{ .Values.timescale.version }}
  template:
    metadata:
      labels:
        app: {{ .Values.timescale.name }}
        version: {{ .Values.timescale.version }}
    spec:
      containers:
      - name: {{ .Values.timescale.name }}
        image: {{ .Values.timescale.container.image }}
        ports:
        - containerPort: {{ .Values.timescale.container.port }}
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ .Values.timescale.config.name }}
        volumeMounts:
        - name: {{ .Values.timescale.volume.name }}
          mountPath: {{ .Values.timescale.volume.mountPath }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.timescale.volume.name }}
    spec:
      accessModes:
      - {{ .Values.timescale.volume.pvc.accessMode }}
      storageClassName: {{ .Values.timescale.volume.pvc.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.timescale.volume.pvc.storage }}
